spring:
  datasource:
    url: jdbc:mysql://localhost:3306/quartz_scheduler
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
  quartz:
    job-store-type: jdbc
    jdbc:
      initialize-schema: never
server:
  port: 9595
